theme: minima
title: Github Training Week
author: zachsopata
email: zachary.sopata@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here to learn as much as I can about git and github so that I can continue down my path of computer engineering!

# social links
# DO NOT include the @ character, or else the build will fail!
github_username:  zachsopata # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
